services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5342:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
    networks:
      - envoy-network
  app:
    image: golang:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GRPC_PORT=${GRPC_PORT}
      - REST_PORT=${REST_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - envoy-network
volumes:
  postgres_data:

networks:
  envoy-network:
    driver: bridge